version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "gomod"
    directory: "/src"
    schedule:
      interval: "daily"

  - package-ecosystem: "go"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase