version: '3'

services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
      
volumes:
  mongo-data: