FROM golang:latest

WORKDIR /app

RUN apt-get update && apt-get install -y \
    vim \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/* \
    && go install github.com/cespare/reflex@latest

COPY go.mod go.sum ./

RUN go mod tidy

COPY . .

EXPOSE 80

CMD ["reflex", "-r", "\\.go$", "go", "run", "main.go"]
